AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Cloud formation test of how far we can push the permission thing
Resources:
  LambdaWebPageLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: test-cf
      Handler: index.handler
      Runtime: nodejs6.10
      Description: test cf
      MemorySize: 128
      Timeout: 30
      CodeUri: s3://chris-build-00-oregon-public/test-cf/build-output/test-cf~0.1.0.zip