AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Set up API Gateway endpoint connected to Lambda function that returns HTML
Resources:
 EncryptionServiceIAMRole:
        Type: "AWS::IAM::Role"
        Properties:
            Path: "/"
            ManagedPolicyArns:
                - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
                - "arn:aws:iam::<account_number>:policy/PHD-FullAccess-WideOrg" # customer managed policy
            AssumeRolePolicyDocument:
              Version: "2012-10-17"
              Statement:
                -
                  Sid: "AllowLambdaServiceToAssumeRole"
                  Effect: "Allow"
                  Action: 
                    - "sts:AssumeRole"
                  Principal:
                    Service: 
                      - "lambda.amazonaws.com"
   
  LambdaWebPageLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: test-cf
      Policies: AWSLambdaDynamoDBExecutionRole
      Handler: index.handler
      Runtime: nodejs6.10
      Description: test cf
      MemorySize: 128
      Timeout: 30
      CodeUri: s3://chris-build-00-oregon-public/lambda-web-page-example/build-output-master/lambda-web-page-example~0.1.10.zip